//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : eventos
//  @ File Name : Individuo.java
//  @ Date : 30/04/2012
//  @ Author : Tiago
//
//
package br.edu.ifsp.eventos.classes;

import br.edu.ifsp.eventos.classes.dao.IndividuoDAO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Individuo extends Inscrito {

    static void removerIndividuo(Individuo individuo) throws SQLException {
        new IndividuoDAO().excluir(individuo);
    }

    
    private Instituicao instituicao = null;
    private String cpf;
    private String hashCode;
    


    public static ArrayList<Individuo> getListaIndividuo()  {
        ArrayList<Individuo> lista = new ArrayList<Individuo>();
        try {
            lista =  new IndividuoDAO().listarTodos();
        } catch (SQLException ex) {
            Logger.getLogger(Individuo.class.getName()).log(Level.SEVERE, null, ex);
        }
        return lista;
    }
    //Obs: package-private
    static void adicionarIndividuo(Individuo individuo) {
        try {
            System.out.println("adicionarIndividuo: adicionando individuo com id " + individuo.getId());            
            new IndividuoDAO().salvar(individuo);
        } catch (SQLException ex) {
            Logger.getLogger(Individuo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public String getCpf() {
        return cpf;
    }

    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    public Instituicao getInstituicao() {
        return instituicao;
    }

    public void setInstituicao(Instituicao instituicao) {
        this.instituicao = instituicao;
    }
    public String getHashCode() {
        return hashCode;
    }

    public void setHashCode(String hashCode) {
        this.hashCode = hashCode;
    }
}
